// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3w_Rbc8wCmkpwZ37Upn1yw-KMoagEvCc',
    appId: '1:906717038980:web:bb8cc468b04afae58d75d1',
    messagingSenderId: '906717038980',
    projectId: 'sonar-app-e4319',
    authDomain: 'sonar-app-e4319.firebaseapp.com',
    storageBucket: 'sonar-app-e4319.appspot.com',
    measurementId: 'G-XTGML9X9F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTmHoCnHyadu17uwOHk7dN9zY-0iVXLpQ',
    appId: '1:906717038980:android:25dff5a1ac9f580e8d75d1',
    messagingSenderId: '906717038980',
    projectId: 'sonar-app-e4319',
    storageBucket: 'sonar-app-e4319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdCyq9xrs7mEbH6n-eX3-7wDDDRTz1aY',
    appId: '1:906717038980:ios:c3107605a76e75cb8d75d1',
    messagingSenderId: '906717038980',
    projectId: 'sonar-app-e4319',
    storageBucket: 'sonar-app-e4319.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest',
  );
}
